def anglesep_meeus(
    lon0: float, lat0: float, lon1: float, lat1: float, deg: bool = True
) -> float: ...
def anglesep(
    lon0: float, lat0: float, lon1: float, lat1: float, deg: bool = True
) -> float: ...
def haversine(theta: float) -> float: ...
