from typing import Optional
from pymap3d.ellipsoid import Ellipsoid

def cart2pol(x, y) -> tuple[float, float]: ...
def pol2cart(theta, rho) -> tuple[float, float]: ...
def cart2sph(x, y, z) -> tuple[float, float, float]: ...
def sph2cart(az, el, r) -> tuple[float, float, float]: ...
def sanitize(
    lat: float, ell: Optional[Ellipsoid], deg: bool
) -> tuple[float, Ellipsoid]: ...
